behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_costmap_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
      simulate_ahead_time: 1.0
      max_rotational_vel: 1.0
      min_rotational_vel: 0.2
      rotational_acc_lim: 3.0
    backup:
      plugin: "nav2_behaviors::BackUp"
      simulate_ahead_time: 1.0
      backup.acceleration_limit: 2.5
      backup.deceleration_limit: -2.5
      backup.minimum_speed: 0.1
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
      simulate_ahead_time: 1.0
      drive_on_heading.acceleration_limit: 2.5
      drive_on_heading.deceleration_limit: -2.5
      drive_on_heading.minimum_speed: 0.2
    wait:
      plugin: "nav2_behaviors::Wait"
      wait_duration: 2.0
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1