controller_server:
  ros__parameters:
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01
    use_realtime_priority: false
    odom_topic: "odom"
    odom_duration: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 120.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.05
      stateful: True

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: .5
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.5
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 0.3
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 2.0

      use_collision_detection: true

      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 0.25
      use_cost_regulated_linear_velocity_scaling: false
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: true

      allow_reversing: true

      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 1.0
      max_robot_pose_search_dist: 10.0
      min_distance_to_obstacle: 0.01
      stateful: true    

local_costmap:
  local_costmap:
    ros__parameters:
      footprint_padding: 0.03
      update_frequency: 2.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.22
      resolution: 0.05
      rolling_window: True
      width: 10
      height: 10
      plugins: ["static_layer", "inflation_layer", "obstacle_layer"]
      track_unknown_space: true
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 1.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.1   # ~20 см радиус инфляции
        cost_scaling_factor: 2.0
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        max_obstacle_height: 0.2      # препятствия до 30 см (если только лазер низко)
        obstacle_range: 2.5           # учитываем преп. в радиусе 2.5 м
        raytrace_range: 3.0           # дальность очистки лучом
        observation_sources: "laser"
        laser:
          topic: scan
          sensor_frame: laser_frame
          data_type: LaserScan
          clearing: true
          marking: true
          inf_is_invalid: true

      always_send_full_costmap: True
      introspection_mode: "disabled"