controller_server:
  ros__parameters:
    controller_frequency: 10.0
    costmap_update_timeout: 0.3
    use_realtime_priority: false
    publish_zero_velocity: true
    min_x_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01
    odom_topic: "odom"
    odom_duration: 0.3
    failure_tolerance: 0.1
    search_window: 0.2
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2
      movement_time_allowance: 1200.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.02
      stateful: True

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.3
      rotate_to_heading_angular_vel: 0.6
      use_collision_detection: true

      lookahead_dist: 0.4
      min_lookahead_dist: 0.1
      max_lookahead_dist: 0.8
      lookahead_time: 0.5
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 2.0

      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: true
      cost_scaling_dist: 0.18
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 2.0
      regulated_linear_scaling_min_radius: 0.2
      regulated_linear_scaling_min_speed: 0.1
      use_fixed_curvature_lookahead: true
      curvature_lookahead_dist: 0.25
      
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 1.0
      max_angular_accel: 1.0

      min_distance_to_obstacle: 0.05

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      footprint: "[[0.1175, 0.0865], [0.1175, -0.0865], [-0.1175, -0.0865], [-0.1175, 0.0865]]"
      footprint_padding: 0.01
      resolution: 0.02
      rolling_window: true
      width: 8
      height: 8
      plugins: ["static_layer", "inflation_layer", "obstacle_layer"]
      track_unknown_space: true
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 1.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.18   # радиус инфляции
        cost_scaling_factor: 10.0
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        max_obstacle_height: 0.5      # препятствия до 30 см (если только лазер низко)
        obstacle_range: 2.5           # учитываем преп. в радиусе 2.5 м
        raytrace_range: 3.0           # дальность очистки лучом
        observation_sources: "laser"
        laser:
          topic: /ld_lidar/scan
          sensor_frame: laser_frame
          data_type: LaserScan
          clearing: true
          marking: true
          inf_is_invalid: true

      always_send_full_costmap: True
      introspection_mode: "disabled"