lidar:
  model: LD19
  frame_id: laser_frame
  range_min: 0.1
  range_max: 10.0
  enable_angle_crop: true
  angle_crop_min: -1.5708     # если хотите ограничить до ±90°
  angle_crop_max: +1.5708
comm:
  serial_port: /dev/ttyUSB0
  baudrate: 115200
general:
  debug_mode: false
