planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    costmap_update_timeout: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: 'nav2_navfn_planner::NavfnPlanner'
      use_astar: True
      allow_unknown: True
      tolerance: 1.0

global_costmap:
  global_costmap:
    ros__parameters:
      footprint: "[[0.1175, 0.0865], [0.1175, -0.0865], [-0.1175, -0.0865], [-0.1175, 0.0865]]"
      footprint_padding: 0.01
      update_frequency: 2.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.01
      rolling_window: True
      width: 8
      height: 8
      track_unknown_space: true
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 1.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3
        cost_scaling_factor: 10.0
      always_send_full_costmap: True
      introspection_mode: "disabled"
