planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    use_astar: true
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      use_astar: true
      allow_unknown: true
      tolerance: 5.0  

global_costmap:
  global_costmap:
    ros__parameters:
      footprint_padding: 0.03
      update_frequency: 2.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.22
      resolution: 0.05
      rolling_window: True
      width: 100
      height: 100
      plugins: ["static_layer"]
      track_unknown_space: true
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 1.0
      always_send_full_costmap: True
      introspection_mode: "disabled"
